name: Flutter Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.6.1
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      
      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Build app bundle
        run: flutter build appbundle

